### ISSUE TITLE
Password feature

### ISSUE THREAD

**Issue by easpro** [rcaelers/workrave#132] opened 2019-05-25 15:32 UTC
Workrave should have password protection to prevent users (adults, kids) from tampering with settings.  A password would help reduce repetitive injuries and computer addiction by not letting a user quit the program.  Also, an option to disable Task Manager or not show Workrave in Task Manager.

**Comment by rcaelers** [comment] 2021-04-21 18:37
#290 is a duplicate of this one, but has some comments that explain why it is unlikely that Workrave will get password protection.
So I will close this one in favor of #290

**Comment by rcaelers** [comment] 2021-04-21 18:37
Duplicate of #290

**Closed by rcaelers** 2021-04-21 18:37 UTC
Labels: duplicate, feature
