### ISSUE TITLE
[Enhancement] Notification about workrave software update

### ISSUE THREAD

**Issue by ldarshan1991** [rcaelers/workrave#316] opened 2021-07-11 11:44 UTC
**Describe the bug**
When there is a new software update from workrave, the installed workrave application on our computer should intimate us that there is a new software update present and show a link to download it directly.

**To Reproduce**
1. When a new software update is rolled out by workrave.
2. A notification from the installed workrave application on the computer.
3. And a direct link to download the latest software update.

**Expected behavior**
When a new software update is rolled out by workrave.  the installed workrave application on our computer should intimate us that there is a new software update present and show a link to download it directly

**Screenshots**
NA

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: Windows 10
 - Workrave Version 1.10.1

**Additional context**
I am currently running 1.10.1 and I am not aware that there is a new software update 1.10.45 already available until I was going through the workrave page and figure it out.

**Comment by rcaelers** [comment] 2021-08-24 14:29
Duplicate of #219

**Comment by rcaelers** [comment] 2021-08-24 14:29
An auto update is indeed also on my wishlist

**Closed by rcaelers** 2021-08-24 14:29 UTC
