### ISSUE TITLE
Temporarily set mode to suspend / quiet

### ISSUE THREAD

**Issue by bclephas** [rcaelers/workrave#213] opened 2020-07-27 11:46 UTC
It would be good if Workrave would allow a user to temporarily disable notifications (temporarily set mode to suspend or quiet). When the time expires, the normal mode (or maybe even the previous mode) is restored.

When giving a presentation or someone else is driving my system, I set the mode, but often forget to restore the mode.

Temporarily is then, e.g. 15 minutes, 1 hour, 2 hours, until reboot, until log out, and so on.
I don't mind if this requires a (modal) window and not be part of the context menu.

Some options how the menu item could be named:
* "Temporarily suspend ..." + "Temporarily silence ..."
* Suspend and restore (or set?) normal mode after ...

**Comment by xerus2000** [comment] 2020-08-06 21:17
Duplicate of #98

**Comment by rcaelers** [comment] 2020-08-07 11:24
This is indeed a duplicate. So I am closing this issue.

**Comment by rcaelers** [comment] 2020-08-07 11:24
Duplicate of #98

**Closed by rcaelers** 2020-08-07 11:24 UTC
Labels: feature
