### ISSUE TITLE
Error with Workrave 1.10.45 and Windows XP, Windows 7 and Windows 8.1 compatibility

### ISSUE THREAD

**Issue by DotNetTester** [rcaelers/workrave#320] opened 2021-07-26 19:45 UTC
Compatibility with Windows XP and Windows 8.1 is partially broken with Workrave 1.10.45. There's an error message of "C:\Program Files (x86)\Workrave\lib\workrave-applet64.dll Unable to register the DLL/OCX RegSvr 32 failed with exit code 0x3" during the install. After clicking OK, the install proceeds normally and Workrave runs normally. Despite it working normally afterwards, this error is a bit disconcerting. I can't remember whether or not Windows XP compatibility was fully or partially broken and I haven't tested Windows 7. I look into all that more.

**Comment by rcaelers** [comment] 2021-07-26 19:49
Workrave requires administrator privileges to register workrave-applet64.dll. You can click ignore to continue the installation. Workrave will still function normally. But you cannot activate the applet. This error is not related to Windows XP/7/8 compatibility. I will check if Workrave can skip the applet when you don't have administrator privileges. 
Note that I only test Workrave in Windows 10/11.

**Comment by DeronLJ** [comment] 2021-07-26 22:35
I get the same message in Windows 7. Installation is running with administrator privileges. As DotNetTester mentioned, it does not seem to affect functionality.

**Comment by rcaelers** [comment] 2022-01-29 23:01
While investigating #367, I found that 1.10.45 started using HiDPI function that require Windows 10. Workrave 1.10.50 will restore compatibility with older Windows versions.

**Comment by rcaelers** [comment] 2022-01-29 23:02
Duplicate of #367

**Closed by rcaelers** 2022-01-29 23:02 UTC
Labels: area: packaging, os: windows
