### ISSUE TITLE
[New feature request] Setting the duration of inactivity

### ISSUE THREAD

**Issue by dev-hemul** [rcaelers/workrave#341] opened 2021-09-23 21:37 UTC
Please add a setting that would be responsible for the duration of inactivity
So that I could choose how long it takes for the counter to stop

Windows 10

**Comment by Konzertheld** [comment] 2021-11-07 19:07
Looks like a duplicate of #120.

**Comment by rcaelers** [comment] 2022-01-30 14:50
I agree that this is a duplicate. So I will close this one.

**Comment by rcaelers** [comment] 2022-01-30 14:50
Duplicate of #120.

**Comment by rcaelers** [comment] 2022-01-30 14:51
Duplicate of #120.

**Closed by rcaelers** 2022-01-30 14:51 UTC
Labels: feature, duplicate, area: activity-monitoring
