### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TMNIrish** [rcaelers/workrave#309] opened 2021-06-25 13:45 UTC
[workrave-crashlog.txt](https://github.com/rcaelers/workrave/files/6716532/workrave-crashlog.txt)

**Comment by rcaelers** [comment] 2022-01-29 20:21
I checked the crashlog, it is the same crash as #380

**Comment by rcaelers** [comment] 2022-01-29 20:21
Duplicate of #380

**Closed by rcaelers** 2022-01-29 20:21 UTC
