### ISSUE TITLE
Feature Request: Timed Quiet/Suspended modes that automatically switch back to Normal

### ISSUE THREAD

**Issue by winternet-studio** [rcaelers/workrave#300] opened 2021-05-11 10:57 UTC
A feature that I'm really missing is to be able to say I want to change to quiet/suspended mode for a given amount of time - so that after a given number of hours and minutes it will automatically switch back to normal. It happens so often that I'm sitting in a meeting where I just can't take a break, so I have to switch to quiet mode - and then it sometimes takes days before I realize it's on quiet and get it switched back again - defeating the entire purpose of the program!

I would even say the timed mode should be mandatory - as the program should never permanently be on quiet and defeat the entire purpose.

Since we now have these fancy computers that can do things for us _automatically_ let's take advantage of that! :) Timed features should be the default in _any_ software that deals with temporary modes.

**Comment by rcaelers** [comment] 2021-05-12 18:34
I agree that this would be a very useful feature. So it is likely to happen someday. Not sure how the UI would look like though. Add some predefined durations to the menu? Or show a dialog to ask the user how long the temporary mode should last?

Not that this is a duplicate of #98 . So I will close this issue (though feel free to still comment on my UI question :-)

**Comment by rcaelers** [comment] 2021-05-12 18:34
Duplicate of #98

**Closed by rcaelers** 2021-05-12 18:34 UTC
Labels: duplicate, feature
