### ISSUE TITLE
Feature Suggestion: Don Not Disturb For

### ISSUE THREAD

**Issue by yasaman72** [rcaelers/workrave#426] opened 2022-07-31 09:00 UTC
An option on the taskbar icon to mute the program for a given time. 
The options could be: an hour, two hours, five hours, today

**Comment by Konkrad** [comment] 2022-08-24 15:28
Hello,
have you had a look at #98 ?

**Comment by rcaelers** [comment] 2022-08-28 09:57
This feature is available in 1.11.0-alpha.3 (https://github.com/rcaelers/workrave/releases/tag/v1_11_0_alpha_3). 

I will close this issue as a duplicate of #98. If you have any feedback on this feature, please add it to #98.

**Comment by rcaelers** [comment] 2022-08-28 09:58
Duplicate of #98

**Closed by rcaelers** 2022-08-28 09:57 UTC
