### ISSUE TITLE
What class/module has the logic that decides when it's time for a break?

### ISSUE THREAD

**Issue by epylar** [rcaelers/workrave#102] opened 2018-06-09 15:47 UTC
I'd like to experiment with having workrave modify its breaks based on keyboard and mouse activity.  I find that a combination of time and number of mouse clicks and especially number of keys typed changes the load on my arms quite a bit--I need more breaks when I'm typing quickly than when I'm browsing the web. 

What class/module decides whether it's time for a break?  I think if I have that as a starting point I can figure it out from there.

**Comment by rcaelers** [comment] 2018-08-29 19:15
In v1.10 branch, mainly backend/src/Core.cc and backend/src/BreakControl.cc. Activity monitoring is also located in backend/src.

I closing this issue because it is not a bug/features request. Please mail me directly if you need help.

**Closed by rcaelers** 2018-08-29 19:15 UTC
