### ISSUE TITLE
Install error on Windows 7

### ISSUE THREAD

**Issue by tobiastromm** [rcaelers/workrave#310] opened 2021-06-28 12:31 UTC
Hi, just want to report this error when installing version 1.10.45 on Windows 7.

https://ibb.co/5vxqbf1

This error will show during install, but program will work as expected.

**Comment by rcaelers** [comment] 2021-07-01 16:21
Workrave requires administrator privileges to be able to register the applet. You will get this error if you don't have these rights. You can click 'ignore' and continue the installation, but the applet will not be usable. I will check if I can exclude this step if you don't have administrator privileges.

**Comment by rcaelers** [comment] 2022-01-29 23:03
While investigating #367, I found that 1.10.45 started using HiDPI functions that require Windows 10. Workrave 1.10.50 will restore compatibility with older Windows versions.

**Comment by rcaelers** [comment] 2022-01-29 23:04
Duplicate of  #367.

**Closed by rcaelers** 2022-01-29 23:04 UTC
Labels: area: packaging, os: windows
