### ISSUE TITLE
COVID-19 Remote Working & Interuption during Screenshare

### ISSUE THREAD

**Issue by freetimecoder3** [rcaelers/workrave#278] opened 2021-02-16 12:24 UTC
**Describe the bug**
Hi,  

Perhaps this is asked else where.  But considering the Global impact of COVID 19 and remote working all time. Screen share for discussions are the norm. It would be a HUGE value-add if the pop-ups do not come in when screen is shared, but maybe a few mins post that.

This would be much helpful...

Something like Skype/Teams DND status ?

**To Reproduce**
1. Go to Teams and Share screen with Team or participant.
2. PopUp comes when screen is shared.
3. 

**Expected behavior**
When screen is shared, no pop-ups to be shown. 
May be a few minutes after closure, the pop-ups can be shown.

**Screenshots**
NA

** Linux (please complete the following information in case you encountered the bug on Linux):**
NA

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: Windows 10
 - Workrave Version : 1.10.44

**Additional context**
NA

**Comment by rcaelers** [comment] 2021-02-23 19:30
This seems to be very similar to #226. I will close this issue as a duplicate of #226.

I am not sure how easy it is to detect DND, full screen mode, gaming, screen sharing, etc. But I think it is worth investigating.

**Comment by rcaelers** [comment] 2021-02-23 19:31
Duplicate of #226

**Closed by rcaelers** 2021-02-23 19:30 UTC
